sudo: false

language: java

jdk:
- openjdk11

branches:
  only:
  - develop
  - master
  - "/^v[0-9].*/"

cache:
  directories:
  - "$HOME/.m2"

install: true

before_script:
- export TZ=Europe/Berlin

script: mvn clean verify

deploy:
  provider: releases
  api_key:
    secure: VO2+iyGBmOc3ldCOm4VJVIrn+ARabRVayps9D4Y0XSIHuthAD2L1buuzkESyYD2EqyvYmu1IikIp3FVX4GaF4n3Jxjg4CrYIx/tC8ZFulCxtwfXlfulvPwHlVyTcqHULxKmUeG2iar6WGhtx4BAZRDzqFZdavT0c1ym36q5GtVIuNs3HepFFUqQY2RrjlLMm7pvcW6B3FxerrFRq44HAgRqRFBqyJ/xcuLDHgo/cXcttibed4N76bCJAhoiY4FMAZ0BlSMJSQNOTe1EV99pRE2DtF+g3FWDVac2oaAJ8FoYKnF/qmfpQEQKleo5PLDr8rohkU5sYmxzM1Tk3xAlBdX0WKiIUPUI0jdNxYN7h7bh5IOkRASbOIL718Jb6txmVJEKDgTnrnkKg2XbyluvQ23UjZFaVOsjzVlJ+zmzOnnnGz8Y8NEFbPO5d7Wy87de8yZApShRT3wzwwHpvFSl+kD7rOQbx9WmrrQA4jpCtyyGQgzXz4m/E0zb6w+AI0Iy/b44wNgyrO3dYV1Mn5eWJnl0BISLc0lN7x6JGHX97AUPDPmekSGcOC7RRlHWUvtCX07T0W7ep513SDAQd24SLsgElQ+Go+ohmOFh6TrPxMnEU5gv90/8gO4o/kxeUmOIVJsQtHlGH17qN5+mPHXTqVkVKR1MyfFqv8E1IqR42Tsw=
  file: "./target/*.zip"
  file_glob: true
  skip_cleanup: true
  on:
    repo: mathisdt/hibiscus-watcher
